packages:
  - "apps/*"
  - "packages/*"

# 统一管理所有子包的共同依赖版本
catalog:
  react: ^19.2.5
  react-dom: ^19.2.5
  next: 16.2.4
  typescript: 5.9.2
  eslint: ^9.39.1
  "@types/node": ^22.15.3
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  tailwindcss: ^4.1.15
  "@tailwindcss/postcss": ^4.1.15
