packages:
  - "apps/*"
  - "packages/*"

# 统一管理所有子包的共同依赖版本
catalog:
  react: ^19.2.5
  react-dom: ^19.2.5
  next: 16.2.4
  typescript: 5.9.2
  eslint: ^9.39.1
  "@types/node": ^22.15.3
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  tailwindcss: ^4.1.15
  "@tailwindcss/postcss": ^4.1.15
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  "@radix-ui/react-slot": ^1.2.3
  "@radix-ui/react-label": ^2.1.7
  "@radix-ui/react-separator": ^1.1.7
  "@cloudflare/workers-types": ^4.20260426.1
  "@hono/zod-validator": ^0.7.6
  hono: ^4.12.15
  zod: ^4.1.13
